version: "3.8"

services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        restart: unless-stopped

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        depends_on:
            - test-service
        restart: unless-stopped

    test-service:
        build: ./services/test-service
        ports:
            - "8001:8001"
        restart: unless-stopped
