version: "3.8"

services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app

    local-llm-service:
        build: ./services/local-llm-service
        ports:
            - "8001:8001"
        volumes:
            - ./services/local-llm-service/models:/app/models
        environment:
            - TRANSFORMERS_CACHE=/app/models
            - HF_HOME=/app/models

    mcp-client:
        build: ./services/mcp-client
        ports:
            - "8003:8003"
        volumes:
            - ./services/mcp-client:/app
        depends_on:
            - searxng-api # Ensure API is ready

    # SearXNG metasearch engine
    searxng:
        image: searxng/searxng:latest
        container_name: searxng
        ports:
            - "8080:8080" # Web UI (optional)
        environment:
            - SEARXNG_BIND_ADDRESS=0.0.0.0
            - SEARXNG_SECRET_KEY=change_this_to_a_random_string
        volumes:
            - ./services/searxng:/etc/searxng # Persistent config

    # Custom API wrapper for SearXNG
    searxng-api:
        build: ./services/searxng-api
        ports:
            - "5000:5000" # Expose API to host
        depends_on:
            - searxng # Wait for SearXNG

    # service-placeholder:
    #     build: ./services/service-placeholder
    #     ports:
    #         - "8002:8002"
    #     environment:
    #         - HF_HUB_DISABLE_TELEMETRY=1
    #         - HF_HUB_OFFLINE=0
    #     volumes:
    #         - ~/.cache/huggingface:/root/.cache/huggingface # Cache models between runs
    #         - ./services/service-placeholder:/app

networks:
    default:
        driver: bridge
