version: "3.8"

services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app

    test-service:
        build: ./services/test-service
        ports:
            - "8001:8001"
        volumes:
            - ./services/test-service/models:/app/models
        environment:
            - TRANSFORMERS_CACHE=/app/models
            - HF_HOME=/app/models

    # service-placeholder:
    #     build: ./services/service-placeholder
    #     ports:
    #         - "8002:8002"
    #     environment:
    #         - HF_HUB_DISABLE_TELEMETRY=1
    #         - HF_HUB_OFFLINE=0
    #     volumes:
    #         - ~/.cache/huggingface:/root/.cache/huggingface # Cache models between runs
    #         - ./services/service-placeholder:/app
