version: "3.8"

services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app

    test-service:
        build: ./services/test-service
        ports:
            - "8001:8001"
        environment:
            - HF_HUB_DISABLE_TELEMETRY=1
            - HF_HUB_OFFLINE=0
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface # Cache models between runs
            - ./services/test-service:/app
